increase min call gas limit & rename verificationGas
etherspot/skandha pull request #54
Opened 2023-07-20 11:39 UTC by marie-fourier

…asLimit

## Description

- increased min call gas limit, 21k wasn't enough for native asset transfer in some cases
- renamed verificationGas to verificationGasLimit as per the new test cases

## Types of changes
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Further comments (optional)

-

2023-07-20 14:36 UTC, arddluma approved these changes
LGTM!

2023-07-26 12:25 UTC, ch4r10t33r requested changes

2023-07-26 12:25 UTC, ch4r10t33r commented on packages/executor/src/config.ts
> +  estimationStaticBuffer: 36000,
What is the rational for this 36000? Can this be configurable variable?

2023-07-26 12:26 UTC, ch4r10t33r commented
Pls address the conflicts and update the package version.

2023-08-17 08:11 UTC, ch4r10t33r approved these changes
LGTM

2023-08-17 08:11 UTC, merged